name: nxcalculator
description: "A calculator that fits into the Nothing OS ecosystem of apps."

publish_to: "none"

version: 1.0.0-a+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.0
  intl: ^0.20.2
  math_expressions: ^3.1.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  shared_preferences_platform_interface: ^2.4.1

flutter:
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Ntype-82
      fonts:
        - asset: assets/fonts/NType82-Regular.otf
    - family: LetteraMono
      fonts:
        - asset: assets/fonts/LetteraMonoLL-Regular.otf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
